import { createCasingPool, createDecalPool } from './pools.js';
import { readBestScore } from './settings.js';

export function makeState(width, height) {
  return {
    width: width || 960,
    height: height || 640,
    running: true,
    paused: false,
    over: false,
    level: 1,
    xp: 0,
    xpNext: 100,
    score: 0,
    combo: 0,
    comboTimer: 0,
    grazeCombo: 0,
    grazeTimer: 0,
    bestScore: readBestScore(),
    kills: 0,
    wave: 1,
    waveTime: 0,
    bountyTarget: 7,
    bountyKills: 0,
    bountyReward: 160,
    bountyClaimed: false,
    spawnTimer: 0.5,
    banner: 1.8,
    bannerText: '',
    shake: 0,
    hurtFlash: 0,
    hitstop: 0,
    heartbeatTimer: 0,
    stormAlerted: false,
    stormKills: 0,
    stormHurt: false,
    bossSpawned: false,
    deathSequenceTimer: 0,
    isNewRecord: false,
    coreSpawnTime: 8 + Math.random() * 8,
    coreSpawned: false,
    stats: { shotsFired: 0, shotsHit: 0, damageDealt: 0, crits: 0, coresDetonated: 0, grazes: 0, maxCombo: 0 },
    casings: createCasingPool(),
    casingIndex: 0,
    decals: createDecalPool(),
    decalIndex: 0,
    player: {
      x: (width || 960) / 2,
      y: (height || 640) / 2,
      vx: 0,
      vy: 0,
      r: 15,
      speed: 235,
      hp: 100,
      maxHp: 100,
      energy: 50,
      maxEnergy: 100,
      damage: 26,
      fireRate: 0.18,
      cooldown: 0,
      bulletSpeed: 700,
      bulletSize: 4,
      xpMult: 1,
      aim: 0,
      invulnerable: 0,
      dashCooldown: 0,
      dashPulse: 0,
      overdrive: 0,
      recoil: 0,
      pierce: 0,
      bounces: 0,
      shockwaveDash: false,
      teslaCoil: false,
      reactiveArmor: false,
      highCaliber: false,
      staticTempest: false,
      kineticShrapnel: false,
      overchargeRetaliation: false,
      vulcanMeltdown: false,
      gravitonBulwark: false,
      plasmaMeltdown: false,
      magnetRadius: 165,
      slowTimer: 0,
      dashAmbushTimer: 0,
      overdriveDurationBonus: 0,
      weaponMode: 'standard',
      chargeTime: 0,
      isCharging: false
    },
    bullets: [],
    enemyBullets: [],
    enemies: [],
    orbs: [],
    particles: [],
    shockRings: [],
    lightningArcs: [],
    volatileCores: [],
    barrels: [],
    artilleryTargets: [],
    opticalFlashes: [],
    plasmaZones: [],
    vortices: [],
    spires: [],
    upgradeChoices: [],
    acquiredUpgrades: []
  };
}
